# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 🚀 Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create .env file
      run: |
        touch .env
        echo REACT_APP_API_URL="${{ secrets.REACT_APP_API_URL }}" >> .env
        echo GENERATE_SOURCEMAP=false >> .env

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn run build

    - name: Upload built app
      uses: sand4rt/ftp-deployer@v1.3
      with:
        sftp: true
        host: ${{ secrets.SSH_HOST }}
        port: 22
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        remote_folder: ./web/
        local_folder: ./build/
        cleanup: true
